// Draws facade detail instances generated by details_emit.wgsl.
#include "scene.wgsl"
#include "lighting.wgsl"

struct Inst {
  pos: vec3f, sx: f32,
  ax: vec3f, sy: f32,
  az: vec3f, sz: f32,
  color: u32, accent: u32, flags: u32, _p: u32,
};
struct Bucket { base: u32, kind: u32, _p0: u32, _p1: u32 };

@group(1) @binding(0) var<storage, read> instances: array<Inst>;
@group(1) @binding(1) var<uniform> bucket: Bucket;

// SSAO (half resolution), sampled in screen space.
@group(2) @binding(0) var aoTex: texture_2d<f32>;
@group(2) @binding(1) var aoSampler: sampler;


struct VIn {
  @location(0) pos: vec3f,
  @location(1) normal: vec3f,
  @location(2) uv: vec2f,
  @location(3) part: u32,
  @builtin(instance_index) ii: u32,
};

struct VOut {
  @invariant @builtin(position) pos: vec4f,
  @location(0) world: vec3f,
  @location(1) normal: vec3f,
  @location(2) uv: vec2f,
  @location(3) @interpolate(flat) part: u32,
  @location(4) @interpolate(flat) inst: u32,
  @location(5) clipCur: vec4f,
  @location(6) clipPrev: vec4f,
  @location(7) local: vec3f,
  @location(8) lnormal: vec3f,
};

@vertex
fn vs_depth(v: VIn) -> @invariant @builtin(position) vec4f {
  let I = instances[bucket.base + v.ii];
  let ay = normalize(cross(I.az, I.ax));
  let lp = v.pos * max(vec3f(I.sx, I.sy, I.sz), vec3f(1e-3));
  return frame.viewProj * vec4f(I.pos + I.ax * lp.x + ay * lp.y + I.az * lp.z, 1.0);
}

@vertex
fn vs(v: VIn) -> VOut {
  let idx = bucket.base + v.ii;
  let I = instances[idx];
  let ay = normalize(cross(I.az, I.ax));
  let scl = max(vec3f(I.sx, I.sy, I.sz), vec3f(1e-3));
  let lp = v.pos * scl;
  let w = I.pos + I.ax * lp.x + ay * lp.y + I.az * lp.z;
  var o: VOut;
  o.pos = frame.viewProj * vec4f(w, 1.0);
  o.world = w;
  o.normal = I.ax * (v.normal.x / scl.x) + ay * (v.normal.y / scl.y) + I.az * (v.normal.z / scl.z);
  o.uv = v.uv * vec2f(scl.x, 1.0);
  o.part = v.part;
  o.inst = idx;
  o.clipCur = frame.viewProjNoJitter * vec4f(w, 1.0);
  o.clipPrev = frame.prevViewProj * vec4f(w, 1.0);
  o.local = lp;
  o.lnormal = v.normal;
  return o;
}

struct GOut {
  @location(0) color: vec4f,
  @location(1) normal: vec4f,
  @location(2) velocity: vec2f,
};

@fragment
fn fs(i: VOut, @builtin(front_facing) front: bool) -> GOut {
  g_fragCoord = i.pos;
  g_ao = textureSampleLevel(aoTex, aoSampler, i.pos.xy * frame.invResolution, 0.0).r;
  let I = instances[i.inst];
  var n = normalize(i.normal);
  if (!front) { n = -n; }
  let body = unpack4x8unorm(I.color).rgb;
  let accent = unpack4x8unorm(I.accent).rgb;
  var sf: Surface;
  sf.normal = n;
  sf.albedo = body;
  sf.roughness = 0.65;
  sf.metallic = 0.15;
  sf.reflectivity = 0.3;
  sf.emissive = vec3f(0.0);
  // Grime: darker toward the bottom of each piece, streaky.
  let streak = 0.75 + 0.25 * vnoise2(vec2f(i.uv.x * 3.0, i.world.y * 0.4));
  switch i.part {
    case 1u: {
      sf.albedo = vec3f(0.045, 0.047, 0.05);
      sf.roughness = 0.45;
      sf.metallic = 0.7;
      sf.reflectivity = 0.45;
    }
    case 2u: {
      if ((I.flags & 1u) != 0u) {
        sf.emissive = accent * 4.0;
        sf.albedo = vec3f(0.02);
      }
    }
    case 3u: {
      sf.albedo = vec3f(0.015, 0.02, 0.025);
      sf.roughness = 0.05;
      sf.reflectivity = 0.9;
    }
    case 4u: {
      // Striped fabric.
      let stripe = step(0.5, fract(i.uv.x * 1.5));
      sf.albedo = mix(accent * 0.55, vec3f(0.6, 0.58, 0.55), stripe * 0.6);
      sf.roughness = 0.85;
    }
    case 5u: {
      if ((I.flags & 2u) != 0u) {
        sf.albedo = vec3f(0.02, 0.03, 0.035);
        sf.roughness = 0.06;
        sf.reflectivity = 0.85;
      } else {
        sf.albedo = body * streak;
      }
    }
    case 6u: {
      // Module: wall with a small grid of windows on its outer faces.
      sf.albedo = body * streak;
      let ln = i.lnormal;
      if (abs(ln.y) < 0.5) {
        let q = select(vec2f(i.local.z, i.local.y), vec2f(i.local.x, i.local.y), abs(ln.z) > 0.5);
        let cell = q / vec2f(1.8, 3.0);
        let fr = fract(cell);
        let win = step(0.15, fr.x) * step(fr.x, 0.85) * step(0.3, fr.y) * step(fr.y, 0.8);
        let hh = hash31(u32(floor(cell.x) + 500.0), u32(floor(cell.y) + 500.0), i.inst);
        let lit = step(hh, 0.45) * f32((I.flags & 1u) != 0u);
        sf.albedo = mix(sf.albedo, vec3f(0.02), win);
        sf.roughness = mix(sf.roughness, 0.1, win);
        sf.emissive = accent * win * lit * (0.6 + 1.6 * hh);
      }
    }
    default: {
      sf.albedo = body * streak;
    }
  }
  // Rain: darker, glossier, especially on top faces.
  let wet = frame.wetness * (0.5 + 0.5 * saturate(n.y));
  sf.albedo *= 1.0 - 0.35 * wet;
  sf.roughness = mix(sf.roughness, sf.roughness * 0.35, wet);
  sf.reflectivity = max(sf.reflectivity, 0.5 * wet);
  var o: GOut;
  o.color = vec4f(shade_surface(sf, i.world), 1.0);
  o.normal = vec4f(encode_normal(n), sf.roughness, sf.reflectivity);
  let a = i.clipCur.xy / i.clipCur.w;
  let b = i.clipPrev.xy / i.clipPrev.w;
  o.velocity = (b - a) * vec2f(0.5, -0.5);
  return o;
}
